version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    tty: true
    ports:
      - "11434:11434"
    volumes:
      - ~/.ollama:/root/.ollama

  web:
    build: ./web
    command: ["gunicorn", "nl2sql_project.wsgi:application", "--bind", "0.0.0.0:8000"]
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - ollama

volumes:
  db_data:
