# Generated by Django 4.2 on 2025-09-26 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nl2sql_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers',
        ),
        migrations.AlterModelTable(
            name='order',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='product',
            table='products',
        ),
    ]
